
CREATE LOGIN [PIA] WITH PASSWORD=N'TPPIA', DEFAULT_DATABASE=[TP-PIA], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

USE [TP-PIA]
GO
CREATE USER [PIA] FOR LOGIN [PIA]
GO
USE [TP-PIA]
GO
ALTER ROLE [db_owner] ADD MEMBER [PIA]
GO